# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#publishing-using-gradle

name: Code Inspection

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Qodana - Code Inspection
        uses: JetBrains/qodana-action@v1.0-eap
        timeout-minutes: 10

      # Archives Qodana results to workflow artifacts
      - name: Archive results
        uses: actions/upload-artifact@v2
        with:
          name: qodana-results
          if-no-files-found: error
          path: report

      # Prints Qodana results
      - name: Print results
        run: |
          echo "🎉 Qodana has finished successfully!"
          echo "Download an artifact qodana-results.zip. Code Inspection results are part of file result-allProblems.json."
          echo "________________________________________________________________"
          cat ${GITHUB_WORKSPACE}/report/results/result-allProblems.json

      # Archives Qodana error logs if Qodana fails
      - name: Archive error logs
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: qodana-error-logs
          path: |
            qodana
            results
